/* JEditNumeroBeanInfo - Decompiled by JODE
 * Visit http://jode.sourceforge.net/
 */
package serpro.ppgd.gui.xbeans;
import java.beans.BeanDescriptor;
import java.beans.BeanInfo;
import java.beans.EventSetDescriptor;
import java.beans.IntrospectionException;
import java.beans.Introspector;
import java.beans.MethodDescriptor;
import java.beans.PropertyDescriptor;
import java.beans.SimpleBeanInfo;

public class JEditNumeroBeanInfo extends SimpleBeanInfo
{
  private static PropertyDescriptor[] properties = null;
  private static final int EVENT_ancestorListener = 0;
  private static final int EVENT_componentListener = 1;
  private static final int EVENT_containerListener = 2;
  private static final int EVENT_focusListener = 3;
  private static final int EVENT_hierarchyBoundsListener = 4;
  private static final int EVENT_hierarchyListener = 5;
  private static final int EVENT_inputMethodListener = 6;
  private static final int EVENT_keyListener = 7;
  private static final int EVENT_mouseListener = 8;
  private static final int EVENT_mouseMotionListener = 9;
  private static final int EVENT_mouseWheelListener = 10;
  private static final int EVENT_propertyChangeListener = 11;
  private static final int EVENT_vetoableChangeListener = 12;
  private static final int METHOD_action0 = 0;
  private static final int METHOD_add1 = 1;
  private static final int METHOD_addNotify2 = 2;
  private static final int METHOD_addPropertyChangeListener3 = 3;
  private static final int METHOD_applyComponentOrientation4 = 4;
  private static final int METHOD_areFocusTraversalKeysSet5 = 5;
  private static final int METHOD_bounds6 = 6;
  private static final int METHOD_chamaValidacao7 = 7;
  private static final int METHOD_checkImage8 = 8;
  private static final int METHOD_computeVisibleRect9 = 9;
  private static final int METHOD_contains10 = 10;
  private static final int METHOD_countComponents11 = 11;
  private static final int METHOD_createImage12 = 12;
  private static final int METHOD_createToolTip13 = 13;
  private static final int METHOD_createVolatileImage14 = 14;
  private static final int METHOD_deliverEvent15 = 15;
  private static final int METHOD_disable16 = 16;
  private static final int METHOD_disparaPainelDicasModal17 = 17;
  private static final int METHOD_dispatchEvent18 = 18;
  private static final int METHOD_doLayout19 = 19;
  private static final int METHOD_enable20 = 20;
  private static final int METHOD_enableInputMethods21 = 21;
  private static final int METHOD_findComponentAt22 = 22;
  private static final int METHOD_firePropertyChange23 = 23;
  private static final int METHOD_getActionForKeyStroke24 = 24;
  private static final int METHOD_getBounds25 = 25;
  private static final int METHOD_getClientProperty26 = 26;
  private static final int METHOD_getComponentAt27 = 27;
  private static final int METHOD_getComponentZOrder28 = 28;
  private static final int METHOD_getConditionForKeyStroke29 = 29;
  private static final int METHOD_getDefaultLocale30 = 30;
  private static final int METHOD_getFontMetrics31 = 31;
  private static final int METHOD_getInsets32 = 32;
  private static final int METHOD_getListeners33 = 33;
  private static final int METHOD_getLocation34 = 34;
  private static final int METHOD_getMousePosition35 = 35;
  private static final int METHOD_getPopupLocation36 = 36;
  private static final int METHOD_getPropertyChangeListeners37 = 37;
  private static final int METHOD_getSize38 = 38;
  private static final int METHOD_getToolTipLocation39 = 39;
  private static final int METHOD_getToolTipText40 = 40;
  private static final int METHOD_gotFocus41 = 41;
  private static final int METHOD_grabFocus42 = 42;
  private static final int METHOD_handleEvent43 = 43;
  private static final int METHOD_hasFocus44 = 44;
  private static final int METHOD_hide45 = 45;
  private static final int METHOD_imageUpdate46 = 46;
  private static final int METHOD_implementacaoPropertyChange47 = 47;
  private static final int METHOD_insets48 = 48;
  private static final int METHOD_inside49 = 49;
  private static final int METHOD_invalidate50 = 50;
  private static final int METHOD_isAncestorOf51 = 51;
  private static final int METHOD_isFocusCycleRoot52 = 52;
  private static final int METHOD_isLightweightComponent53 = 53;
  private static final int METHOD_keyDown54 = 54;
  private static final int METHOD_keyUp55 = 55;
  private static final int METHOD_layout56 = 56;
  private static final int METHOD_list57 = 57;
  private static final int METHOD_locate58 = 58;
  private static final int METHOD_location59 = 59;
  private static final int METHOD_lostFocus60 = 60;
  private static final int METHOD_minimumSize61 = 61;
  private static final int METHOD_mouseDown62 = 62;
  private static final int METHOD_mouseDrag63 = 63;
  private static final int METHOD_mouseEnter64 = 64;
  private static final int METHOD_mouseExit65 = 65;
  private static final int METHOD_mouseMove66 = 66;
  private static final int METHOD_mouseUp67 = 67;
  private static final int METHOD_move68 = 68;
  private static final int METHOD_nextFocus69 = 69;
  private static final int METHOD_paint70 = 70;
  private static final int METHOD_paintAll71 = 71;
  private static final int METHOD_paintComponents72 = 72;
  private static final int METHOD_paintImmediately73 = 73;
  private static final int METHOD_postEvent74 = 74;
  private static final int METHOD_preferredSize75 = 75;
  private static final int METHOD_prepareImage76 = 76;
  private static final int METHOD_print77 = 77;
  private static final int METHOD_printAll78 = 78;
  private static final int METHOD_printComponents79 = 79;
  private static final int METHOD_propertyChange80 = 80;
  private static final int METHOD_putClientProperty81 = 81;
  private static final int METHOD_registerKeyboardAction82 = 82;
  private static final int METHOD_remove83 = 83;
  private static final int METHOD_removeAll84 = 84;
  private static final int METHOD_removeNotify85 = 85;
  private static final int METHOD_removePropertyChangeListener86 = 86;
  private static final int METHOD_repaint87 = 87;
  private static final int METHOD_requestDefaultFocus88 = 88;
  private static final int METHOD_requestFocus89 = 89;
  private static final int METHOD_requestFocusInWindow90 = 90;
  private static final int METHOD_resetKeyboardActions91 = 91;
  private static final int METHOD_reshape92 = 92;
  private static final int METHOD_resize93 = 93;
  private static final int METHOD_revalidate94 = 94;
  private static final int METHOD_scrollRectToVisible95 = 95;
  private static final int METHOD_setarCampo96 = 96;
  private static final int METHOD_setBounds97 = 97;
  private static final int METHOD_setComponentZOrder98 = 98;
  private static final int METHOD_setDefaultLocale99 = 99;
  private static final int METHOD_show100 = 100;
  private static final int METHOD_size101 = 101;
  private static final int METHOD_toString102 = 102;
  private static final int METHOD_transferFocus103 = 103;
  private static final int METHOD_transferFocusBackward104 = 104;
  private static final int METHOD_transferFocusDownCycle105 = 105;
  private static final int METHOD_transferFocusUpCycle106 = 106;
  private static final int METHOD_unregisterKeyboardAction107 = 107;
  private static final int METHOD_update108 = 108;
  private static final int METHOD_updateUI109 = 109;
  private static final int METHOD_validate110 = 110;
  private static final int defaultPropertyIndex = -1;
  private static final int defaultEventIndex = -1;
  
  private static BeanDescriptor getBdescriptor ()
  {
    Class var_class = serpro.ppgd.gui.xbeans.JEditNumero.class;
    BeanDescriptor beandescriptor = new BeanDescriptor (var_class, null);
    BeanDescriptor beanDescriptor = beandescriptor;
    return beanDescriptor;
  }
  
  private static PropertyDescriptor[] getPdescriptor ()
  {
    return properties;
  }
  
  private static EventSetDescriptor[] getEdescriptor ()
  {
    EventSetDescriptor[] eventSets = new EventSetDescriptor[13];
    try
      {
	EventSetDescriptor[] eventsetdescriptors = eventSets;
	int i = 0;
	Class var_class = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string = "ancestorListener";
	Class var_class_2_ = javax.swing.event.AncestorListener.class;
	EventSetDescriptor eventsetdescriptor = new EventSetDescriptor (var_class, string, var_class_2_, new String[] { "ancestorAdded", "ancestorMoved", "ancestorRemoved" }, "addAncestorListener", "removeAncestorListener");
	eventsetdescriptors[i] = eventsetdescriptor;
	EventSetDescriptor[] eventsetdescriptors_4_ = eventSets;
	int i_5_ = 1;
	Class var_class_7_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_9_ = "componentListener";
	Class var_class_10_ = java.awt.event.ComponentListener.class;
	EventSetDescriptor eventsetdescriptor_6_ = new EventSetDescriptor (var_class_7_, string_9_, var_class_10_, new String[] { "componentHidden", "componentMoved", "componentResized", "componentShown" }, "addComponentListener", "removeComponentListener");
	eventsetdescriptors_4_[i_5_] = eventsetdescriptor_6_;
	EventSetDescriptor[] eventsetdescriptors_12_ = eventSets;
	int i_13_ = 2;
	Class var_class_15_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_17_ = "containerListener";
	Class var_class_18_ = java.awt.event.ContainerListener.class;
	EventSetDescriptor eventsetdescriptor_14_ = new EventSetDescriptor (var_class_15_, string_17_, var_class_18_, new String[] { "componentAdded", "componentRemoved" }, "addContainerListener", "removeContainerListener");
	eventsetdescriptors_12_[i_13_] = eventsetdescriptor_14_;
	EventSetDescriptor[] eventsetdescriptors_20_ = eventSets;
	int i_21_ = 3;
	Class var_class_23_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_25_ = "focusListener";
	Class var_class_26_ = java.awt.event.FocusListener.class;
	EventSetDescriptor eventsetdescriptor_22_ = new EventSetDescriptor (var_class_23_, string_25_, var_class_26_, new String[] { "focusGained", "focusLost" }, "addFocusListener", "removeFocusListener");
	eventsetdescriptors_20_[i_21_] = eventsetdescriptor_22_;
	EventSetDescriptor[] eventsetdescriptors_28_ = eventSets;
	int i_29_ = 4;
	Class var_class_31_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_33_ = "hierarchyBoundsListener";
	Class var_class_34_ = java.awt.event.HierarchyBoundsListener.class;
	EventSetDescriptor eventsetdescriptor_30_ = new EventSetDescriptor (var_class_31_, string_33_, var_class_34_, new String[] { "ancestorMoved", "ancestorResized" }, "addHierarchyBoundsListener", "removeHierarchyBoundsListener");
	eventsetdescriptors_28_[i_29_] = eventsetdescriptor_30_;
	EventSetDescriptor[] eventsetdescriptors_36_ = eventSets;
	int i_37_ = 5;
	Class var_class_39_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_41_ = "hierarchyListener";
	Class var_class_42_ = java.awt.event.HierarchyListener.class;
	EventSetDescriptor eventsetdescriptor_38_ = new EventSetDescriptor (var_class_39_, string_41_, var_class_42_, new String[] { "hierarchyChanged" }, "addHierarchyListener", "removeHierarchyListener");
	eventsetdescriptors_36_[i_37_] = eventsetdescriptor_38_;
	EventSetDescriptor[] eventsetdescriptors_44_ = eventSets;
	int i_45_ = 6;
	Class var_class_47_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_49_ = "inputMethodListener";
	Class var_class_50_ = java.awt.event.InputMethodListener.class;
	EventSetDescriptor eventsetdescriptor_46_ = new EventSetDescriptor (var_class_47_, string_49_, var_class_50_, new String[] { "caretPositionChanged", "inputMethodTextChanged" }, "addInputMethodListener", "removeInputMethodListener");
	eventsetdescriptors_44_[i_45_] = eventsetdescriptor_46_;
	EventSetDescriptor[] eventsetdescriptors_52_ = eventSets;
	int i_53_ = 7;
	Class var_class_55_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_57_ = "keyListener";
	Class var_class_58_ = java.awt.event.KeyListener.class;
	EventSetDescriptor eventsetdescriptor_54_ = new EventSetDescriptor (var_class_55_, string_57_, var_class_58_, new String[] { "keyPressed", "keyReleased", "keyTyped" }, "addKeyListener", "removeKeyListener");
	eventsetdescriptors_52_[i_53_] = eventsetdescriptor_54_;
	EventSetDescriptor[] eventsetdescriptors_60_ = eventSets;
	int i_61_ = 8;
	Class var_class_63_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_65_ = "mouseListener";
	Class var_class_66_ = java.awt.event.MouseListener.class;
	EventSetDescriptor eventsetdescriptor_62_ = new EventSetDescriptor (var_class_63_, string_65_, var_class_66_, new String[] { "mouseClicked", "mouseEntered", "mouseExited", "mousePressed", "mouseReleased" }, "addMouseListener", "removeMouseListener");
	eventsetdescriptors_60_[i_61_] = eventsetdescriptor_62_;
	EventSetDescriptor[] eventsetdescriptors_68_ = eventSets;
	int i_69_ = 9;
	Class var_class_71_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_73_ = "mouseMotionListener";
	Class var_class_74_ = java.awt.event.MouseMotionListener.class;
	EventSetDescriptor eventsetdescriptor_70_ = new EventSetDescriptor (var_class_71_, string_73_, var_class_74_, new String[] { "mouseDragged", "mouseMoved" }, "addMouseMotionListener", "removeMouseMotionListener");
	eventsetdescriptors_68_[i_69_] = eventsetdescriptor_70_;
	EventSetDescriptor[] eventsetdescriptors_76_ = eventSets;
	int i_77_ = 10;
	Class var_class_79_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_81_ = "mouseWheelListener";
	Class var_class_82_ = java.awt.event.MouseWheelListener.class;
	EventSetDescriptor eventsetdescriptor_78_ = new EventSetDescriptor (var_class_79_, string_81_, var_class_82_, new String[] { "mouseWheelMoved" }, "addMouseWheelListener", "removeMouseWheelListener");
	eventsetdescriptors_76_[i_77_] = eventsetdescriptor_78_;
	EventSetDescriptor[] eventsetdescriptors_84_ = eventSets;
	int i_85_ = 11;
	Class var_class_87_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_89_ = "propertyChangeListener";
	Class var_class_90_ = java.beans.PropertyChangeListener.class;
	EventSetDescriptor eventsetdescriptor_86_ = new EventSetDescriptor (var_class_87_, string_89_, var_class_90_, new String[] { "propertyChange" }, "addPropertyChangeListener", "removePropertyChangeListener");
	eventsetdescriptors_84_[i_85_] = eventsetdescriptor_86_;
	EventSetDescriptor[] eventsetdescriptors_92_ = eventSets;
	int i_93_ = 12;
	Class var_class_95_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_97_ = "vetoableChangeListener";
	Class var_class_98_ = java.beans.VetoableChangeListener.class;
	EventSetDescriptor eventsetdescriptor_94_ = new EventSetDescriptor (var_class_95_, string_97_, var_class_98_, new String[] { "vetoableChange" }, "addVetoableChangeListener", "removeVetoableChangeListener");
	eventsetdescriptors_92_[i_93_] = eventsetdescriptor_94_;
      }
    catch (IntrospectionException e)
      {
	e.printStackTrace ();
      }
    return eventSets;
  }
  
  private static MethodDescriptor[] getMdescriptor ()
  {
    MethodDescriptor[] methods = new MethodDescriptor[111];
    try
      {
	MethodDescriptor[] methoddescriptors = methods;
	int i = 0;
	Class var_class = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string = "action";
	Class[] var_classes = new Class[2];
	int i_101_ = 0;
	Class var_class_102_ = java.awt.Event.class;
	var_classes[i_101_] = var_class_102_;
	int i_104_ = 1;
	Class var_class_105_ = java.lang.Object.class;
	var_classes[i_104_] = var_class_105_;
	MethodDescriptor methoddescriptor = new MethodDescriptor (var_class.getMethod (string, var_classes));
	methoddescriptors[i] = methoddescriptor;
	methods[0].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_107_ = methods;
	int i_108_ = 1;
	Class var_class_110_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_112_ = "add";
	Class[] var_classes_113_ = new Class[1];
	int i_114_ = 0;
	Class var_class_115_ = java.awt.Component.class;
	var_classes_113_[i_114_] = var_class_115_;
	MethodDescriptor methoddescriptor_109_ = new MethodDescriptor (var_class_110_.getMethod (string_112_, var_classes_113_));
	methoddescriptors_107_[i_108_] = methoddescriptor_109_;
	methods[1].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_117_ = methods;
	int i_118_ = 2;
	Class var_class_120_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_119_ = new MethodDescriptor (var_class_120_.getMethod ("addNotify", new Class[0]));
	methoddescriptors_117_[i_118_] = methoddescriptor_119_;
	methods[2].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_122_ = methods;
	int i_123_ = 3;
	Class var_class_125_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_127_ = "addPropertyChangeListener";
	Class[] var_classes_128_ = new Class[2];
	int i_129_ = 0;
	Class var_class_130_ = java.lang.String.class;
	var_classes_128_[i_129_] = var_class_130_;
	int i_132_ = 1;
	Class var_class_133_ = java.beans.PropertyChangeListener.class;
	var_classes_128_[i_132_] = var_class_133_;
	MethodDescriptor methoddescriptor_124_ = new MethodDescriptor (var_class_125_.getMethod (string_127_, var_classes_128_));
	methoddescriptors_122_[i_123_] = methoddescriptor_124_;
	methods[3].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_135_ = methods;
	int i_136_ = 4;
	Class var_class_138_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_140_ = "applyComponentOrientation";
	Class[] var_classes_141_ = new Class[1];
	int i_142_ = 0;
	Class var_class_143_ = java.awt.ComponentOrientation.class;
	var_classes_141_[i_142_] = var_class_143_;
	MethodDescriptor methoddescriptor_137_ = new MethodDescriptor (var_class_138_.getMethod (string_140_, var_classes_141_));
	methoddescriptors_135_[i_136_] = methoddescriptor_137_;
	methods[4].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_145_ = methods;
	int i_146_ = 5;
	Class var_class_148_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_147_ = new MethodDescriptor (var_class_148_.getMethod ("areFocusTraversalKeysSet", new Class[] { Integer.TYPE }));
	methoddescriptors_145_[i_146_] = methoddescriptor_147_;
	methods[5].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_150_ = methods;
	int i_151_ = 6;
	Class var_class_153_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_152_ = new MethodDescriptor (var_class_153_.getMethod ("bounds", new Class[0]));
	methoddescriptors_150_[i_151_] = methoddescriptor_152_;
	methods[6].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_155_ = methods;
	int i_156_ = 7;
	Class var_class_158_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_157_ = new MethodDescriptor (var_class_158_.getMethod ("chamaValidacao", new Class[0]));
	methoddescriptors_155_[i_156_] = methoddescriptor_157_;
	methods[7].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_160_ = methods;
	int i_161_ = 8;
	Class var_class_163_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_165_ = "checkImage";
	Class[] var_classes_166_ = new Class[2];
	int i_167_ = 0;
	Class var_class_168_ = java.awt.Image.class;
	var_classes_166_[i_167_] = var_class_168_;
	int i_170_ = 1;
	Class var_class_171_ = java.awt.image.ImageObserver.class;
	var_classes_166_[i_170_] = var_class_171_;
	MethodDescriptor methoddescriptor_162_ = new MethodDescriptor (var_class_163_.getMethod (string_165_, var_classes_166_));
	methoddescriptors_160_[i_161_] = methoddescriptor_162_;
	methods[8].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_173_ = methods;
	int i_174_ = 9;
	Class var_class_176_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_178_ = "computeVisibleRect";
	Class[] var_classes_179_ = new Class[1];
	int i_180_ = 0;
	Class var_class_181_ = java.awt.Rectangle.class;
	var_classes_179_[i_180_] = var_class_181_;
	MethodDescriptor methoddescriptor_175_ = new MethodDescriptor (var_class_176_.getMethod (string_178_, var_classes_179_));
	methoddescriptors_173_[i_174_] = methoddescriptor_175_;
	methods[9].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_183_ = methods;
	int i_184_ = 10;
	Class var_class_186_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_185_ = new MethodDescriptor (var_class_186_.getMethod ("contains", new Class[] { Integer.TYPE, Integer.TYPE }));
	methoddescriptors_183_[i_184_] = methoddescriptor_185_;
	methods[10].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_188_ = methods;
	int i_189_ = 11;
	Class var_class_191_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_190_ = new MethodDescriptor (var_class_191_.getMethod ("countComponents", new Class[0]));
	methoddescriptors_188_[i_189_] = methoddescriptor_190_;
	methods[11].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_193_ = methods;
	int i_194_ = 12;
	Class var_class_196_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_198_ = "createImage";
	Class[] var_classes_199_ = new Class[1];
	int i_200_ = 0;
	Class var_class_201_ = java.awt.image.ImageProducer.class;
	var_classes_199_[i_200_] = var_class_201_;
	MethodDescriptor methoddescriptor_195_ = new MethodDescriptor (var_class_196_.getMethod (string_198_, var_classes_199_));
	methoddescriptors_193_[i_194_] = methoddescriptor_195_;
	methods[12].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_203_ = methods;
	int i_204_ = 13;
	Class var_class_206_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_205_ = new MethodDescriptor (var_class_206_.getMethod ("createToolTip", new Class[0]));
	methoddescriptors_203_[i_204_] = methoddescriptor_205_;
	methods[13].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_208_ = methods;
	int i_209_ = 14;
	Class var_class_211_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_210_ = new MethodDescriptor (var_class_211_.getMethod ("createVolatileImage", new Class[] { Integer.TYPE, Integer.TYPE }));
	methoddescriptors_208_[i_209_] = methoddescriptor_210_;
	methods[14].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_213_ = methods;
	int i_214_ = 15;
	Class var_class_216_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_218_ = "deliverEvent";
	Class[] var_classes_219_ = new Class[1];
	int i_220_ = 0;
	Class var_class_221_ = java.awt.Event.class;
	var_classes_219_[i_220_] = var_class_221_;
	MethodDescriptor methoddescriptor_215_ = new MethodDescriptor (var_class_216_.getMethod (string_218_, var_classes_219_));
	methoddescriptors_213_[i_214_] = methoddescriptor_215_;
	methods[15].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_223_ = methods;
	int i_224_ = 16;
	Class var_class_226_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_225_ = new MethodDescriptor (var_class_226_.getMethod ("disable", new Class[0]));
	methoddescriptors_223_[i_224_] = methoddescriptor_225_;
	methods[16].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_228_ = methods;
	int i_229_ = 17;
	Class var_class_231_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_230_ = new MethodDescriptor (var_class_231_.getMethod ("disparaPainelDicasModal", new Class[0]));
	methoddescriptors_228_[i_229_] = methoddescriptor_230_;
	methods[17].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_233_ = methods;
	int i_234_ = 18;
	Class var_class_236_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_238_ = "dispatchEvent";
	Class[] var_classes_239_ = new Class[1];
	int i_240_ = 0;
	Class var_class_241_ = java.awt.AWTEvent.class;
	var_classes_239_[i_240_] = var_class_241_;
	MethodDescriptor methoddescriptor_235_ = new MethodDescriptor (var_class_236_.getMethod (string_238_, var_classes_239_));
	methoddescriptors_233_[i_234_] = methoddescriptor_235_;
	methods[18].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_243_ = methods;
	int i_244_ = 19;
	Class var_class_246_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_245_ = new MethodDescriptor (var_class_246_.getMethod ("doLayout", new Class[0]));
	methoddescriptors_243_[i_244_] = methoddescriptor_245_;
	methods[19].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_248_ = methods;
	int i_249_ = 20;
	Class var_class_251_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_250_ = new MethodDescriptor (var_class_251_.getMethod ("enable", new Class[0]));
	methoddescriptors_248_[i_249_] = methoddescriptor_250_;
	methods[20].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_253_ = methods;
	int i_254_ = 21;
	Class var_class_256_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_255_ = new MethodDescriptor (var_class_256_.getMethod ("enableInputMethods", new Class[] { Boolean.TYPE }));
	methoddescriptors_253_[i_254_] = methoddescriptor_255_;
	methods[21].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_258_ = methods;
	int i_259_ = 22;
	Class var_class_261_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_260_ = new MethodDescriptor (var_class_261_.getMethod ("findComponentAt", new Class[] { Integer.TYPE, Integer.TYPE }));
	methoddescriptors_258_[i_259_] = methoddescriptor_260_;
	methods[22].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_263_ = methods;
	int i_264_ = 23;
	Class var_class_266_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_268_ = "firePropertyChange";
	Class[] var_classes_269_ = new Class[3];
	int i_270_ = 0;
	Class var_class_271_ = java.lang.String.class;
	var_classes_269_[i_270_] = var_class_271_;
	var_classes_269_[1] = Boolean.TYPE;
	var_classes_269_[2] = Boolean.TYPE;
	MethodDescriptor methoddescriptor_265_ = new MethodDescriptor (var_class_266_.getMethod (string_268_, var_classes_269_));
	methoddescriptors_263_[i_264_] = methoddescriptor_265_;
	methods[23].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_273_ = methods;
	int i_274_ = 24;
	Class var_class_276_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_278_ = "getActionForKeyStroke";
	Class[] var_classes_279_ = new Class[1];
	int i_280_ = 0;
	Class var_class_281_ = javax.swing.KeyStroke.class;
	var_classes_279_[i_280_] = var_class_281_;
	MethodDescriptor methoddescriptor_275_ = new MethodDescriptor (var_class_276_.getMethod (string_278_, var_classes_279_));
	methoddescriptors_273_[i_274_] = methoddescriptor_275_;
	methods[24].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_283_ = methods;
	int i_284_ = 25;
	Class var_class_286_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_288_ = "getBounds";
	Class[] var_classes_289_ = new Class[1];
	int i_290_ = 0;
	Class var_class_291_ = java.awt.Rectangle.class;
	var_classes_289_[i_290_] = var_class_291_;
	MethodDescriptor methoddescriptor_285_ = new MethodDescriptor (var_class_286_.getMethod (string_288_, var_classes_289_));
	methoddescriptors_283_[i_284_] = methoddescriptor_285_;
	methods[25].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_293_ = methods;
	int i_294_ = 26;
	Class var_class_296_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_298_ = "getClientProperty";
	Class[] var_classes_299_ = new Class[1];
	int i_300_ = 0;
	Class var_class_301_ = java.lang.Object.class;
	var_classes_299_[i_300_] = var_class_301_;
	MethodDescriptor methoddescriptor_295_ = new MethodDescriptor (var_class_296_.getMethod (string_298_, var_classes_299_));
	methoddescriptors_293_[i_294_] = methoddescriptor_295_;
	methods[26].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_303_ = methods;
	int i_304_ = 27;
	Class var_class_306_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_305_ = new MethodDescriptor (var_class_306_.getMethod ("getComponentAt", new Class[] { Integer.TYPE, Integer.TYPE }));
	methoddescriptors_303_[i_304_] = methoddescriptor_305_;
	methods[27].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_308_ = methods;
	int i_309_ = 28;
	Class var_class_311_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_313_ = "getComponentZOrder";
	Class[] var_classes_314_ = new Class[1];
	int i_315_ = 0;
	Class var_class_316_ = java.awt.Component.class;
	var_classes_314_[i_315_] = var_class_316_;
	MethodDescriptor methoddescriptor_310_ = new MethodDescriptor (var_class_311_.getMethod (string_313_, var_classes_314_));
	methoddescriptors_308_[i_309_] = methoddescriptor_310_;
	methods[28].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_318_ = methods;
	int i_319_ = 29;
	Class var_class_321_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_323_ = "getConditionForKeyStroke";
	Class[] var_classes_324_ = new Class[1];
	int i_325_ = 0;
	Class var_class_326_ = javax.swing.KeyStroke.class;
	var_classes_324_[i_325_] = var_class_326_;
	MethodDescriptor methoddescriptor_320_ = new MethodDescriptor (var_class_321_.getMethod (string_323_, var_classes_324_));
	methoddescriptors_318_[i_319_] = methoddescriptor_320_;
	methods[29].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_328_ = methods;
	int i_329_ = 30;
	Class var_class_331_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_330_ = new MethodDescriptor (var_class_331_.getMethod ("getDefaultLocale", new Class[0]));
	methoddescriptors_328_[i_329_] = methoddescriptor_330_;
	methods[30].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_333_ = methods;
	int i_334_ = 31;
	Class var_class_336_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_338_ = "getFontMetrics";
	Class[] var_classes_339_ = new Class[1];
	int i_340_ = 0;
	Class var_class_341_ = java.awt.Font.class;
	var_classes_339_[i_340_] = var_class_341_;
	MethodDescriptor methoddescriptor_335_ = new MethodDescriptor (var_class_336_.getMethod (string_338_, var_classes_339_));
	methoddescriptors_333_[i_334_] = methoddescriptor_335_;
	methods[31].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_343_ = methods;
	int i_344_ = 32;
	Class var_class_346_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_348_ = "getInsets";
	Class[] var_classes_349_ = new Class[1];
	int i_350_ = 0;
	Class var_class_351_ = java.awt.Insets.class;
	var_classes_349_[i_350_] = var_class_351_;
	MethodDescriptor methoddescriptor_345_ = new MethodDescriptor (var_class_346_.getMethod (string_348_, var_classes_349_));
	methoddescriptors_343_[i_344_] = methoddescriptor_345_;
	methods[32].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_353_ = methods;
	int i_354_ = 33;
	Class var_class_356_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_358_ = "getListeners";
	Class[] var_classes_359_ = new Class[1];
	int i_360_ = 0;
	Class var_class_361_ = java.lang.Class.class;
	var_classes_359_[i_360_] = var_class_361_;
	MethodDescriptor methoddescriptor_355_ = new MethodDescriptor (var_class_356_.getMethod (string_358_, var_classes_359_));
	methoddescriptors_353_[i_354_] = methoddescriptor_355_;
	methods[33].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_363_ = methods;
	int i_364_ = 34;
	Class var_class_366_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_368_ = "getLocation";
	Class[] var_classes_369_ = new Class[1];
	int i_370_ = 0;
	Class var_class_371_ = java.awt.Point.class;
	var_classes_369_[i_370_] = var_class_371_;
	MethodDescriptor methoddescriptor_365_ = new MethodDescriptor (var_class_366_.getMethod (string_368_, var_classes_369_));
	methoddescriptors_363_[i_364_] = methoddescriptor_365_;
	methods[34].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_373_ = methods;
	int i_374_ = 35;
	Class var_class_376_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_375_ = new MethodDescriptor (var_class_376_.getMethod ("getMousePosition", new Class[] { Boolean.TYPE }));
	methoddescriptors_373_[i_374_] = methoddescriptor_375_;
	methods[35].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_378_ = methods;
	int i_379_ = 36;
	Class var_class_381_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_383_ = "getPopupLocation";
	Class[] var_classes_384_ = new Class[1];
	int i_385_ = 0;
	Class var_class_386_ = java.awt.event.MouseEvent.class;
	var_classes_384_[i_385_] = var_class_386_;
	MethodDescriptor methoddescriptor_380_ = new MethodDescriptor (var_class_381_.getMethod (string_383_, var_classes_384_));
	methoddescriptors_378_[i_379_] = methoddescriptor_380_;
	methods[36].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_388_ = methods;
	int i_389_ = 37;
	Class var_class_391_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_393_ = "getPropertyChangeListeners";
	Class[] var_classes_394_ = new Class[1];
	int i_395_ = 0;
	Class var_class_396_ = java.lang.String.class;
	var_classes_394_[i_395_] = var_class_396_;
	MethodDescriptor methoddescriptor_390_ = new MethodDescriptor (var_class_391_.getMethod (string_393_, var_classes_394_));
	methoddescriptors_388_[i_389_] = methoddescriptor_390_;
	methods[37].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_398_ = methods;
	int i_399_ = 38;
	Class var_class_401_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_403_ = "getSize";
	Class[] var_classes_404_ = new Class[1];
	int i_405_ = 0;
	Class var_class_406_ = java.awt.Dimension.class;
	var_classes_404_[i_405_] = var_class_406_;
	MethodDescriptor methoddescriptor_400_ = new MethodDescriptor (var_class_401_.getMethod (string_403_, var_classes_404_));
	methoddescriptors_398_[i_399_] = methoddescriptor_400_;
	methods[38].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_408_ = methods;
	int i_409_ = 39;
	Class var_class_411_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_413_ = "getToolTipLocation";
	Class[] var_classes_414_ = new Class[1];
	int i_415_ = 0;
	Class var_class_416_ = java.awt.event.MouseEvent.class;
	var_classes_414_[i_415_] = var_class_416_;
	MethodDescriptor methoddescriptor_410_ = new MethodDescriptor (var_class_411_.getMethod (string_413_, var_classes_414_));
	methoddescriptors_408_[i_409_] = methoddescriptor_410_;
	methods[39].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_418_ = methods;
	int i_419_ = 40;
	Class var_class_421_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_423_ = "getToolTipText";
	Class[] var_classes_424_ = new Class[1];
	int i_425_ = 0;
	Class var_class_426_ = java.awt.event.MouseEvent.class;
	var_classes_424_[i_425_] = var_class_426_;
	MethodDescriptor methoddescriptor_420_ = new MethodDescriptor (var_class_421_.getMethod (string_423_, var_classes_424_));
	methoddescriptors_418_[i_419_] = methoddescriptor_420_;
	methods[40].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_428_ = methods;
	int i_429_ = 41;
	Class var_class_431_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_433_ = "gotFocus";
	Class[] var_classes_434_ = new Class[2];
	int i_435_ = 0;
	Class var_class_436_ = java.awt.Event.class;
	var_classes_434_[i_435_] = var_class_436_;
	int i_438_ = 1;
	Class var_class_439_ = java.lang.Object.class;
	var_classes_434_[i_438_] = var_class_439_;
	MethodDescriptor methoddescriptor_430_ = new MethodDescriptor (var_class_431_.getMethod (string_433_, var_classes_434_));
	methoddescriptors_428_[i_429_] = methoddescriptor_430_;
	methods[41].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_441_ = methods;
	int i_442_ = 42;
	Class var_class_444_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_443_ = new MethodDescriptor (var_class_444_.getMethod ("grabFocus", new Class[0]));
	methoddescriptors_441_[i_442_] = methoddescriptor_443_;
	methods[42].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_446_ = methods;
	int i_447_ = 43;
	Class var_class_449_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_451_ = "handleEvent";
	Class[] var_classes_452_ = new Class[1];
	int i_453_ = 0;
	Class var_class_454_ = java.awt.Event.class;
	var_classes_452_[i_453_] = var_class_454_;
	MethodDescriptor methoddescriptor_448_ = new MethodDescriptor (var_class_449_.getMethod (string_451_, var_classes_452_));
	methoddescriptors_446_[i_447_] = methoddescriptor_448_;
	methods[43].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_456_ = methods;
	int i_457_ = 44;
	Class var_class_459_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_458_ = new MethodDescriptor (var_class_459_.getMethod ("hasFocus", new Class[0]));
	methoddescriptors_456_[i_457_] = methoddescriptor_458_;
	methods[44].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_461_ = methods;
	int i_462_ = 45;
	Class var_class_464_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_463_ = new MethodDescriptor (var_class_464_.getMethod ("hide", new Class[0]));
	methoddescriptors_461_[i_462_] = methoddescriptor_463_;
	methods[45].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_466_ = methods;
	int i_467_ = 46;
	Class var_class_469_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_471_ = "imageUpdate";
	Class[] var_classes_472_ = new Class[6];
	int i_473_ = 0;
	Class var_class_474_ = java.awt.Image.class;
	var_classes_472_[i_473_] = var_class_474_;
	var_classes_472_[1] = Integer.TYPE;
	var_classes_472_[2] = Integer.TYPE;
	var_classes_472_[3] = Integer.TYPE;
	var_classes_472_[4] = Integer.TYPE;
	var_classes_472_[5] = Integer.TYPE;
	MethodDescriptor methoddescriptor_468_ = new MethodDescriptor (var_class_469_.getMethod (string_471_, var_classes_472_));
	methoddescriptors_466_[i_467_] = methoddescriptor_468_;
	methods[46].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_476_ = methods;
	int i_477_ = 47;
	Class var_class_479_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_481_ = "implementacaoPropertyChange";
	Class[] var_classes_482_ = new Class[1];
	int i_483_ = 0;
	Class var_class_484_ = java.beans.PropertyChangeEvent.class;
	var_classes_482_[i_483_] = var_class_484_;
	MethodDescriptor methoddescriptor_478_ = new MethodDescriptor (var_class_479_.getMethod (string_481_, var_classes_482_));
	methoddescriptors_476_[i_477_] = methoddescriptor_478_;
	methods[47].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_486_ = methods;
	int i_487_ = 48;
	Class var_class_489_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_488_ = new MethodDescriptor (var_class_489_.getMethod ("insets", new Class[0]));
	methoddescriptors_486_[i_487_] = methoddescriptor_488_;
	methods[48].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_491_ = methods;
	int i_492_ = 49;
	Class var_class_494_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_493_ = new MethodDescriptor (var_class_494_.getMethod ("inside", new Class[] { Integer.TYPE, Integer.TYPE }));
	methoddescriptors_491_[i_492_] = methoddescriptor_493_;
	methods[49].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_496_ = methods;
	int i_497_ = 50;
	Class var_class_499_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_498_ = new MethodDescriptor (var_class_499_.getMethod ("invalidate", new Class[0]));
	methoddescriptors_496_[i_497_] = methoddescriptor_498_;
	methods[50].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_501_ = methods;
	int i_502_ = 51;
	Class var_class_504_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_506_ = "isAncestorOf";
	Class[] var_classes_507_ = new Class[1];
	int i_508_ = 0;
	Class var_class_509_ = java.awt.Component.class;
	var_classes_507_[i_508_] = var_class_509_;
	MethodDescriptor methoddescriptor_503_ = new MethodDescriptor (var_class_504_.getMethod (string_506_, var_classes_507_));
	methoddescriptors_501_[i_502_] = methoddescriptor_503_;
	methods[51].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_511_ = methods;
	int i_512_ = 52;
	Class var_class_514_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_516_ = "isFocusCycleRoot";
	Class[] var_classes_517_ = new Class[1];
	int i_518_ = 0;
	Class var_class_519_ = java.awt.Container.class;
	var_classes_517_[i_518_] = var_class_519_;
	MethodDescriptor methoddescriptor_513_ = new MethodDescriptor (var_class_514_.getMethod (string_516_, var_classes_517_));
	methoddescriptors_511_[i_512_] = methoddescriptor_513_;
	methods[52].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_521_ = methods;
	int i_522_ = 53;
	Class var_class_524_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_526_ = "isLightweightComponent";
	Class[] var_classes_527_ = new Class[1];
	int i_528_ = 0;
	Class var_class_529_ = java.awt.Component.class;
	var_classes_527_[i_528_] = var_class_529_;
	MethodDescriptor methoddescriptor_523_ = new MethodDescriptor (var_class_524_.getMethod (string_526_, var_classes_527_));
	methoddescriptors_521_[i_522_] = methoddescriptor_523_;
	methods[53].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_531_ = methods;
	int i_532_ = 54;
	Class var_class_534_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_536_ = "keyDown";
	Class[] var_classes_537_ = new Class[2];
	int i_538_ = 0;
	Class var_class_539_ = java.awt.Event.class;
	var_classes_537_[i_538_] = var_class_539_;
	var_classes_537_[1] = Integer.TYPE;
	MethodDescriptor methoddescriptor_533_ = new MethodDescriptor (var_class_534_.getMethod (string_536_, var_classes_537_));
	methoddescriptors_531_[i_532_] = methoddescriptor_533_;
	methods[54].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_541_ = methods;
	int i_542_ = 55;
	Class var_class_544_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_546_ = "keyUp";
	Class[] var_classes_547_ = new Class[2];
	int i_548_ = 0;
	Class var_class_549_ = java.awt.Event.class;
	var_classes_547_[i_548_] = var_class_549_;
	var_classes_547_[1] = Integer.TYPE;
	MethodDescriptor methoddescriptor_543_ = new MethodDescriptor (var_class_544_.getMethod (string_546_, var_classes_547_));
	methoddescriptors_541_[i_542_] = methoddescriptor_543_;
	methods[55].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_551_ = methods;
	int i_552_ = 56;
	Class var_class_554_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_553_ = new MethodDescriptor (var_class_554_.getMethod ("layout", new Class[0]));
	methoddescriptors_551_[i_552_] = methoddescriptor_553_;
	methods[56].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_556_ = methods;
	int i_557_ = 57;
	Class var_class_559_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_561_ = "list";
	Class[] var_classes_562_ = new Class[2];
	int i_563_ = 0;
	Class var_class_564_ = java.io.PrintStream.class;
	var_classes_562_[i_563_] = var_class_564_;
	var_classes_562_[1] = Integer.TYPE;
	MethodDescriptor methoddescriptor_558_ = new MethodDescriptor (var_class_559_.getMethod (string_561_, var_classes_562_));
	methoddescriptors_556_[i_557_] = methoddescriptor_558_;
	methods[57].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_566_ = methods;
	int i_567_ = 58;
	Class var_class_569_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_568_ = new MethodDescriptor (var_class_569_.getMethod ("locate", new Class[] { Integer.TYPE, Integer.TYPE }));
	methoddescriptors_566_[i_567_] = methoddescriptor_568_;
	methods[58].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_571_ = methods;
	int i_572_ = 59;
	Class var_class_574_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_573_ = new MethodDescriptor (var_class_574_.getMethod ("location", new Class[0]));
	methoddescriptors_571_[i_572_] = methoddescriptor_573_;
	methods[59].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_576_ = methods;
	int i_577_ = 60;
	Class var_class_579_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_581_ = "lostFocus";
	Class[] var_classes_582_ = new Class[2];
	int i_583_ = 0;
	Class var_class_584_ = java.awt.Event.class;
	var_classes_582_[i_583_] = var_class_584_;
	int i_586_ = 1;
	Class var_class_587_ = java.lang.Object.class;
	var_classes_582_[i_586_] = var_class_587_;
	MethodDescriptor methoddescriptor_578_ = new MethodDescriptor (var_class_579_.getMethod (string_581_, var_classes_582_));
	methoddescriptors_576_[i_577_] = methoddescriptor_578_;
	methods[60].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_589_ = methods;
	int i_590_ = 61;
	Class var_class_592_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_591_ = new MethodDescriptor (var_class_592_.getMethod ("minimumSize", new Class[0]));
	methoddescriptors_589_[i_590_] = methoddescriptor_591_;
	methods[61].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_594_ = methods;
	int i_595_ = 62;
	Class var_class_597_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_599_ = "mouseDown";
	Class[] var_classes_600_ = new Class[3];
	int i_601_ = 0;
	Class var_class_602_ = java.awt.Event.class;
	var_classes_600_[i_601_] = var_class_602_;
	var_classes_600_[1] = Integer.TYPE;
	var_classes_600_[2] = Integer.TYPE;
	MethodDescriptor methoddescriptor_596_ = new MethodDescriptor (var_class_597_.getMethod (string_599_, var_classes_600_));
	methoddescriptors_594_[i_595_] = methoddescriptor_596_;
	methods[62].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_604_ = methods;
	int i_605_ = 63;
	Class var_class_607_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_609_ = "mouseDrag";
	Class[] var_classes_610_ = new Class[3];
	int i_611_ = 0;
	Class var_class_612_ = java.awt.Event.class;
	var_classes_610_[i_611_] = var_class_612_;
	var_classes_610_[1] = Integer.TYPE;
	var_classes_610_[2] = Integer.TYPE;
	MethodDescriptor methoddescriptor_606_ = new MethodDescriptor (var_class_607_.getMethod (string_609_, var_classes_610_));
	methoddescriptors_604_[i_605_] = methoddescriptor_606_;
	methods[63].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_614_ = methods;
	int i_615_ = 64;
	Class var_class_617_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_619_ = "mouseEnter";
	Class[] var_classes_620_ = new Class[3];
	int i_621_ = 0;
	Class var_class_622_ = java.awt.Event.class;
	var_classes_620_[i_621_] = var_class_622_;
	var_classes_620_[1] = Integer.TYPE;
	var_classes_620_[2] = Integer.TYPE;
	MethodDescriptor methoddescriptor_616_ = new MethodDescriptor (var_class_617_.getMethod (string_619_, var_classes_620_));
	methoddescriptors_614_[i_615_] = methoddescriptor_616_;
	methods[64].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_624_ = methods;
	int i_625_ = 65;
	Class var_class_627_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_629_ = "mouseExit";
	Class[] var_classes_630_ = new Class[3];
	int i_631_ = 0;
	Class var_class_632_ = java.awt.Event.class;
	var_classes_630_[i_631_] = var_class_632_;
	var_classes_630_[1] = Integer.TYPE;
	var_classes_630_[2] = Integer.TYPE;
	MethodDescriptor methoddescriptor_626_ = new MethodDescriptor (var_class_627_.getMethod (string_629_, var_classes_630_));
	methoddescriptors_624_[i_625_] = methoddescriptor_626_;
	methods[65].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_634_ = methods;
	int i_635_ = 66;
	Class var_class_637_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_639_ = "mouseMove";
	Class[] var_classes_640_ = new Class[3];
	int i_641_ = 0;
	Class var_class_642_ = java.awt.Event.class;
	var_classes_640_[i_641_] = var_class_642_;
	var_classes_640_[1] = Integer.TYPE;
	var_classes_640_[2] = Integer.TYPE;
	MethodDescriptor methoddescriptor_636_ = new MethodDescriptor (var_class_637_.getMethod (string_639_, var_classes_640_));
	methoddescriptors_634_[i_635_] = methoddescriptor_636_;
	methods[66].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_644_ = methods;
	int i_645_ = 67;
	Class var_class_647_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_649_ = "mouseUp";
	Class[] var_classes_650_ = new Class[3];
	int i_651_ = 0;
	Class var_class_652_ = java.awt.Event.class;
	var_classes_650_[i_651_] = var_class_652_;
	var_classes_650_[1] = Integer.TYPE;
	var_classes_650_[2] = Integer.TYPE;
	MethodDescriptor methoddescriptor_646_ = new MethodDescriptor (var_class_647_.getMethod (string_649_, var_classes_650_));
	methoddescriptors_644_[i_645_] = methoddescriptor_646_;
	methods[67].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_654_ = methods;
	int i_655_ = 68;
	Class var_class_657_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_656_ = new MethodDescriptor (var_class_657_.getMethod ("move", new Class[] { Integer.TYPE, Integer.TYPE }));
	methoddescriptors_654_[i_655_] = methoddescriptor_656_;
	methods[68].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_659_ = methods;
	int i_660_ = 69;
	Class var_class_662_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_661_ = new MethodDescriptor (var_class_662_.getMethod ("nextFocus", new Class[0]));
	methoddescriptors_659_[i_660_] = methoddescriptor_661_;
	methods[69].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_664_ = methods;
	int i_665_ = 70;
	Class var_class_667_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_669_ = "paint";
	Class[] var_classes_670_ = new Class[1];
	int i_671_ = 0;
	Class var_class_672_ = java.awt.Graphics.class;
	var_classes_670_[i_671_] = var_class_672_;
	MethodDescriptor methoddescriptor_666_ = new MethodDescriptor (var_class_667_.getMethod (string_669_, var_classes_670_));
	methoddescriptors_664_[i_665_] = methoddescriptor_666_;
	methods[70].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_674_ = methods;
	int i_675_ = 71;
	Class var_class_677_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_679_ = "paintAll";
	Class[] var_classes_680_ = new Class[1];
	int i_681_ = 0;
	Class var_class_682_ = java.awt.Graphics.class;
	var_classes_680_[i_681_] = var_class_682_;
	MethodDescriptor methoddescriptor_676_ = new MethodDescriptor (var_class_677_.getMethod (string_679_, var_classes_680_));
	methoddescriptors_674_[i_675_] = methoddescriptor_676_;
	methods[71].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_684_ = methods;
	int i_685_ = 72;
	Class var_class_687_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_689_ = "paintComponents";
	Class[] var_classes_690_ = new Class[1];
	int i_691_ = 0;
	Class var_class_692_ = java.awt.Graphics.class;
	var_classes_690_[i_691_] = var_class_692_;
	MethodDescriptor methoddescriptor_686_ = new MethodDescriptor (var_class_687_.getMethod (string_689_, var_classes_690_));
	methoddescriptors_684_[i_685_] = methoddescriptor_686_;
	methods[72].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_694_ = methods;
	int i_695_ = 73;
	Class var_class_697_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_696_ = new MethodDescriptor (var_class_697_.getMethod ("paintImmediately", new Class[] { Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE }));
	methoddescriptors_694_[i_695_] = methoddescriptor_696_;
	methods[73].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_699_ = methods;
	int i_700_ = 74;
	Class var_class_702_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_704_ = "postEvent";
	Class[] var_classes_705_ = new Class[1];
	int i_706_ = 0;
	Class var_class_707_ = java.awt.Event.class;
	var_classes_705_[i_706_] = var_class_707_;
	MethodDescriptor methoddescriptor_701_ = new MethodDescriptor (var_class_702_.getMethod (string_704_, var_classes_705_));
	methoddescriptors_699_[i_700_] = methoddescriptor_701_;
	methods[74].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_709_ = methods;
	int i_710_ = 75;
	Class var_class_712_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_711_ = new MethodDescriptor (var_class_712_.getMethod ("preferredSize", new Class[0]));
	methoddescriptors_709_[i_710_] = methoddescriptor_711_;
	methods[75].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_714_ = methods;
	int i_715_ = 76;
	Class var_class_717_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_719_ = "prepareImage";
	Class[] var_classes_720_ = new Class[2];
	int i_721_ = 0;
	Class var_class_722_ = java.awt.Image.class;
	var_classes_720_[i_721_] = var_class_722_;
	int i_724_ = 1;
	Class var_class_725_ = java.awt.image.ImageObserver.class;
	var_classes_720_[i_724_] = var_class_725_;
	MethodDescriptor methoddescriptor_716_ = new MethodDescriptor (var_class_717_.getMethod (string_719_, var_classes_720_));
	methoddescriptors_714_[i_715_] = methoddescriptor_716_;
	methods[76].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_727_ = methods;
	int i_728_ = 77;
	Class var_class_730_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_732_ = "print";
	Class[] var_classes_733_ = new Class[1];
	int i_734_ = 0;
	Class var_class_735_ = java.awt.Graphics.class;
	var_classes_733_[i_734_] = var_class_735_;
	MethodDescriptor methoddescriptor_729_ = new MethodDescriptor (var_class_730_.getMethod (string_732_, var_classes_733_));
	methoddescriptors_727_[i_728_] = methoddescriptor_729_;
	methods[77].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_737_ = methods;
	int i_738_ = 78;
	Class var_class_740_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_742_ = "printAll";
	Class[] var_classes_743_ = new Class[1];
	int i_744_ = 0;
	Class var_class_745_ = java.awt.Graphics.class;
	var_classes_743_[i_744_] = var_class_745_;
	MethodDescriptor methoddescriptor_739_ = new MethodDescriptor (var_class_740_.getMethod (string_742_, var_classes_743_));
	methoddescriptors_737_[i_738_] = methoddescriptor_739_;
	methods[78].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_747_ = methods;
	int i_748_ = 79;
	Class var_class_750_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_752_ = "printComponents";
	Class[] var_classes_753_ = new Class[1];
	int i_754_ = 0;
	Class var_class_755_ = java.awt.Graphics.class;
	var_classes_753_[i_754_] = var_class_755_;
	MethodDescriptor methoddescriptor_749_ = new MethodDescriptor (var_class_750_.getMethod (string_752_, var_classes_753_));
	methoddescriptors_747_[i_748_] = methoddescriptor_749_;
	methods[79].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_757_ = methods;
	int i_758_ = 80;
	Class var_class_760_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_762_ = "propertyChange";
	Class[] var_classes_763_ = new Class[1];
	int i_764_ = 0;
	Class var_class_765_ = java.beans.PropertyChangeEvent.class;
	var_classes_763_[i_764_] = var_class_765_;
	MethodDescriptor methoddescriptor_759_ = new MethodDescriptor (var_class_760_.getMethod (string_762_, var_classes_763_));
	methoddescriptors_757_[i_758_] = methoddescriptor_759_;
	methods[80].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_767_ = methods;
	int i_768_ = 81;
	Class var_class_770_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_772_ = "putClientProperty";
	Class[] var_classes_773_ = new Class[2];
	int i_774_ = 0;
	Class var_class_775_ = java.lang.Object.class;
	var_classes_773_[i_774_] = var_class_775_;
	int i_777_ = 1;
	Class var_class_778_ = java.lang.Object.class;
	var_classes_773_[i_777_] = var_class_778_;
	MethodDescriptor methoddescriptor_769_ = new MethodDescriptor (var_class_770_.getMethod (string_772_, var_classes_773_));
	methoddescriptors_767_[i_768_] = methoddescriptor_769_;
	methods[81].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_780_ = methods;
	int i_781_ = 82;
	Class var_class_783_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_785_ = "registerKeyboardAction";
	Class[] var_classes_786_ = new Class[4];
	int i_787_ = 0;
	Class var_class_788_ = java.awt.event.ActionListener.class;
	var_classes_786_[i_787_] = var_class_788_;
	int i_790_ = 1;
	Class var_class_791_ = java.lang.String.class;
	var_classes_786_[i_790_] = var_class_791_;
	int i_793_ = 2;
	Class var_class_794_ = javax.swing.KeyStroke.class;
	var_classes_786_[i_793_] = var_class_794_;
	var_classes_786_[3] = Integer.TYPE;
	MethodDescriptor methoddescriptor_782_ = new MethodDescriptor (var_class_783_.getMethod (string_785_, var_classes_786_));
	methoddescriptors_780_[i_781_] = methoddescriptor_782_;
	methods[82].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_796_ = methods;
	int i_797_ = 83;
	Class var_class_799_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_798_ = new MethodDescriptor (var_class_799_.getMethod ("remove", new Class[] { Integer.TYPE }));
	methoddescriptors_796_[i_797_] = methoddescriptor_798_;
	methods[83].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_801_ = methods;
	int i_802_ = 84;
	Class var_class_804_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_803_ = new MethodDescriptor (var_class_804_.getMethod ("removeAll", new Class[0]));
	methoddescriptors_801_[i_802_] = methoddescriptor_803_;
	methods[84].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_806_ = methods;
	int i_807_ = 85;
	Class var_class_809_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_808_ = new MethodDescriptor (var_class_809_.getMethod ("removeNotify", new Class[0]));
	methoddescriptors_806_[i_807_] = methoddescriptor_808_;
	methods[85].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_811_ = methods;
	int i_812_ = 86;
	Class var_class_814_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_816_ = "removePropertyChangeListener";
	Class[] var_classes_817_ = new Class[2];
	int i_818_ = 0;
	Class var_class_819_ = java.lang.String.class;
	var_classes_817_[i_818_] = var_class_819_;
	int i_821_ = 1;
	Class var_class_822_ = java.beans.PropertyChangeListener.class;
	var_classes_817_[i_821_] = var_class_822_;
	MethodDescriptor methoddescriptor_813_ = new MethodDescriptor (var_class_814_.getMethod (string_816_, var_classes_817_));
	methoddescriptors_811_[i_812_] = methoddescriptor_813_;
	methods[86].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_824_ = methods;
	int i_825_ = 87;
	Class var_class_827_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_826_ = new MethodDescriptor (var_class_827_.getMethod ("repaint", new Class[] { Long.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE }));
	methoddescriptors_824_[i_825_] = methoddescriptor_826_;
	methods[87].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_829_ = methods;
	int i_830_ = 88;
	Class var_class_832_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_831_ = new MethodDescriptor (var_class_832_.getMethod ("requestDefaultFocus", new Class[0]));
	methoddescriptors_829_[i_830_] = methoddescriptor_831_;
	methods[88].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_834_ = methods;
	int i_835_ = 89;
	Class var_class_837_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_836_ = new MethodDescriptor (var_class_837_.getMethod ("requestFocus", new Class[0]));
	methoddescriptors_834_[i_835_] = methoddescriptor_836_;
	methods[89].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_839_ = methods;
	int i_840_ = 90;
	Class var_class_842_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_841_ = new MethodDescriptor (var_class_842_.getMethod ("requestFocusInWindow", new Class[0]));
	methoddescriptors_839_[i_840_] = methoddescriptor_841_;
	methods[90].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_844_ = methods;
	int i_845_ = 91;
	Class var_class_847_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_846_ = new MethodDescriptor (var_class_847_.getMethod ("resetKeyboardActions", new Class[0]));
	methoddescriptors_844_[i_845_] = methoddescriptor_846_;
	methods[91].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_849_ = methods;
	int i_850_ = 92;
	Class var_class_852_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_851_ = new MethodDescriptor (var_class_852_.getMethod ("reshape", new Class[] { Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE }));
	methoddescriptors_849_[i_850_] = methoddescriptor_851_;
	methods[92].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_854_ = methods;
	int i_855_ = 93;
	Class var_class_857_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_856_ = new MethodDescriptor (var_class_857_.getMethod ("resize", new Class[] { Integer.TYPE, Integer.TYPE }));
	methoddescriptors_854_[i_855_] = methoddescriptor_856_;
	methods[93].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_859_ = methods;
	int i_860_ = 94;
	Class var_class_862_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_861_ = new MethodDescriptor (var_class_862_.getMethod ("revalidate", new Class[0]));
	methoddescriptors_859_[i_860_] = methoddescriptor_861_;
	methods[94].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_864_ = methods;
	int i_865_ = 95;
	Class var_class_867_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_869_ = "scrollRectToVisible";
	Class[] var_classes_870_ = new Class[1];
	int i_871_ = 0;
	Class var_class_872_ = java.awt.Rectangle.class;
	var_classes_870_[i_871_] = var_class_872_;
	MethodDescriptor methoddescriptor_866_ = new MethodDescriptor (var_class_867_.getMethod (string_869_, var_classes_870_));
	methoddescriptors_864_[i_865_] = methoddescriptor_866_;
	methods[95].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_874_ = methods;
	int i_875_ = 96;
	Class var_class_877_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_876_ = new MethodDescriptor (var_class_877_.getMethod ("setarCampo", new Class[0]));
	methoddescriptors_874_[i_875_] = methoddescriptor_876_;
	methods[96].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_879_ = methods;
	int i_880_ = 97;
	Class var_class_882_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_881_ = new MethodDescriptor (var_class_882_.getMethod ("setBounds", new Class[] { Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE }));
	methoddescriptors_879_[i_880_] = methoddescriptor_881_;
	methods[97].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_884_ = methods;
	int i_885_ = 98;
	Class var_class_887_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_889_ = "setComponentZOrder";
	Class[] var_classes_890_ = new Class[2];
	int i_891_ = 0;
	Class var_class_892_ = java.awt.Component.class;
	var_classes_890_[i_891_] = var_class_892_;
	var_classes_890_[1] = Integer.TYPE;
	MethodDescriptor methoddescriptor_886_ = new MethodDescriptor (var_class_887_.getMethod (string_889_, var_classes_890_));
	methoddescriptors_884_[i_885_] = methoddescriptor_886_;
	methods[98].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_894_ = methods;
	int i_895_ = 99;
	Class var_class_897_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_899_ = "setDefaultLocale";
	Class[] var_classes_900_ = new Class[1];
	int i_901_ = 0;
	Class var_class_902_ = java.util.Locale.class;
	var_classes_900_[i_901_] = var_class_902_;
	MethodDescriptor methoddescriptor_896_ = new MethodDescriptor (var_class_897_.getMethod (string_899_, var_classes_900_));
	methoddescriptors_894_[i_895_] = methoddescriptor_896_;
	methods[99].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_904_ = methods;
	int i_905_ = 100;
	Class var_class_907_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_906_ = new MethodDescriptor (var_class_907_.getMethod ("show", new Class[0]));
	methoddescriptors_904_[i_905_] = methoddescriptor_906_;
	methods[100].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_909_ = methods;
	int i_910_ = 101;
	Class var_class_912_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_911_ = new MethodDescriptor (var_class_912_.getMethod ("size", new Class[0]));
	methoddescriptors_909_[i_910_] = methoddescriptor_911_;
	methods[101].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_914_ = methods;
	int i_915_ = 102;
	Class var_class_917_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_916_ = new MethodDescriptor (var_class_917_.getMethod ("toString", new Class[0]));
	methoddescriptors_914_[i_915_] = methoddescriptor_916_;
	methods[102].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_919_ = methods;
	int i_920_ = 103;
	Class var_class_922_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_921_ = new MethodDescriptor (var_class_922_.getMethod ("transferFocus", new Class[0]));
	methoddescriptors_919_[i_920_] = methoddescriptor_921_;
	methods[103].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_924_ = methods;
	int i_925_ = 104;
	Class var_class_927_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_926_ = new MethodDescriptor (var_class_927_.getMethod ("transferFocusBackward", new Class[0]));
	methoddescriptors_924_[i_925_] = methoddescriptor_926_;
	methods[104].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_929_ = methods;
	int i_930_ = 105;
	Class var_class_932_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_931_ = new MethodDescriptor (var_class_932_.getMethod ("transferFocusDownCycle", new Class[0]));
	methoddescriptors_929_[i_930_] = methoddescriptor_931_;
	methods[105].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_934_ = methods;
	int i_935_ = 106;
	Class var_class_937_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_936_ = new MethodDescriptor (var_class_937_.getMethod ("transferFocusUpCycle", new Class[0]));
	methoddescriptors_934_[i_935_] = methoddescriptor_936_;
	methods[106].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_939_ = methods;
	int i_940_ = 107;
	Class var_class_942_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_944_ = "unregisterKeyboardAction";
	Class[] var_classes_945_ = new Class[1];
	int i_946_ = 0;
	Class var_class_947_ = javax.swing.KeyStroke.class;
	var_classes_945_[i_946_] = var_class_947_;
	MethodDescriptor methoddescriptor_941_ = new MethodDescriptor (var_class_942_.getMethod (string_944_, var_classes_945_));
	methoddescriptors_939_[i_940_] = methoddescriptor_941_;
	methods[107].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_949_ = methods;
	int i_950_ = 108;
	Class var_class_952_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	String string_954_ = "update";
	Class[] var_classes_955_ = new Class[1];
	int i_956_ = 0;
	Class var_class_957_ = java.awt.Graphics.class;
	var_classes_955_[i_956_] = var_class_957_;
	MethodDescriptor methoddescriptor_951_ = new MethodDescriptor (var_class_952_.getMethod (string_954_, var_classes_955_));
	methoddescriptors_949_[i_950_] = methoddescriptor_951_;
	methods[108].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_959_ = methods;
	int i_960_ = 109;
	Class var_class_962_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_961_ = new MethodDescriptor (var_class_962_.getMethod ("updateUI", new Class[0]));
	methoddescriptors_959_[i_960_] = methoddescriptor_961_;
	methods[109].setDisplayName ("");
	MethodDescriptor[] methoddescriptors_964_ = methods;
	int i_965_ = 110;
	Class var_class_967_ = serpro.ppgd.gui.xbeans.JEditNumero.class;
	MethodDescriptor methoddescriptor_966_ = new MethodDescriptor (var_class_967_.getMethod ("validate", new Class[0]));
	methoddescriptors_964_[i_965_] = methoddescriptor_966_;
	methods[110].setDisplayName ("");
      }
    catch (Exception exception)
      {
	/* empty */
      }
    return methods;
  }
  
  public BeanInfo[] getAdditionalBeanInfo ()
  {
    Class var_class = serpro.ppgd.gui.xbeans.JEditNumero.class;
    Class superclass = var_class.getSuperclass ();
    BeanInfo sbi = null;
    try
      {
	sbi = Introspector.getBeanInfo (superclass);
      }
    catch (IntrospectionException introspectionexception)
      {
	/* empty */
      }
    return new BeanInfo[] { sbi };
  }
  
  public BeanDescriptor getBeanDescriptor ()
  {
    return getBdescriptor ();
  }
  
  public PropertyDescriptor[] getPropertyDescriptors ()
  {
    return getPdescriptor ();
  }
  
  public EventSetDescriptor[] getEventSetDescriptors ()
  {
    return getEdescriptor ();
  }
  
  public MethodDescriptor[] getMethodDescriptors ()
  {
    return getMdescriptor ();
  }
  
  public int getDefaultPropertyIndex ()
  {
    return -1;
  }
  
  public int getDefaultEventIndex ()
  {
    return -1;
  }
}
