#! /bin/sh

set -e

ver=`ls freed-ora-*.src.rpm 2>/dev/null | sed s,.src.rpm$,, || :`

if test -n "$ver"; then
  echo NOT re-creating $ver.src.rpm
else
  rpmbuild --define "_sourcedir `pwd`" --define "_srcrpmdir `pwd`" -bs freed-ora.spec
  ver=`ls freed-ora-*.src.rpm | sed s,.src.rpm$,,`
fi
ls $ver.src.rpm

build --ver $ver || exit

dist=master
svndir=`svn info | sed -n 's,^URL: ,,p'`
svnrepo=`echo $svndir | sed -n 's,^\(.*/linux-libre/freed-ora\)/\(freed-ora-pkg\).*,\1,p'`

case `svn info $svnrepo/tags/$dist/$ver 2>&1` in
*"$svnrepo/tags/$dist/$ver"*"non-existent"*)
  : ;;
*)
  echo $ver already tagged >&2
  exit 1
  ;;
esac

until rpm --resign *.noarch/*.rpm; do :; done
svn commit -m "$ver"
svn cp -m "tag $ver" $svndir $svnrepo/tags/$dist/$ver
