#! /bin/sh

#Usage: ./deblob-check-patches [--verbose] patch-* *.patch

#Currently define possible firmware to be 32 or more comma seperated
#consecutive constants

case $1 in
--verbose |-v)
  verbose=true; shift
  ;;
*)
  verbose=false
  ;;
esac

if $verbose; then
  verbose_msg="suspicious sequences above found in"
  verbose_grep=
else
  verbose_msg=
  verbose_grep=-q
fi

xcat () {
  sedx=
  case /$1 in
  */patch*2.6.25-rc*.bz2)
    sedx='
    /\$3 = {{pge = /,/<repeats 11 times>}/d;
    /dtc-lexer.lex.c_shipped$/,/^diff/d;
    /dtc-parser.tab.c_shipped$/,/^diff/d;
    /int bcomm_irq\[/,/};$/d;
    /static const int8 countLeadingZerosHigh\[/,/};$/d;
    /^static unsigned long shmedia_opcode_table\[/,/^};$/d;
    /static struct .*_testvec .*_tv_template\[/,/^};$/d;
    /^static struct nic_qp_map nic_qp_mapping_0\[/,/^};$/d;
    /^static u8 mt2266_init2\[/,/^};$/d;
    /err = sn9c102_write_const_regs(cam/,/);/d;
    /^static struct regval stk1125_initvals\[/,/^};$/d;
    /^static u8 bnx2x_stats_len_arr\[/,/^};$/d;
    /^static const u16 rtl8225bcd_rxgain\[/,/^};$/d;
    /^static const u8 rtl8225_agc\[/,/^};$/d;
    /^static const u8 rtl8225_tx_power_cck\[/,/^};$/d;
    /^static const u8 rtl8225_tx_power_cck_ch14\[/,/^};$/d;
    /^static const u16 rtl8225z2_rxgain\[/,/^};$/d;
    / static uchar sbox\[/,/^};$/d;
    /^static const u16 e1000_igp_2_cable_length_table\[/,/^};$/d;
    / kconf_id_hash (register const char/,/^@@/d;
    /^static const unsigned char wm_vol\[/,/^};$/d;
    '
    ;;
  */linux-2.6-lirc.patch)
    sedx='/^const unsigned char map_table/,/^};$/d'
    ;;
  */linux-2.6-modsign-mpilib.patch)
    sedx='/^const unsigned char __clz_tab/,/^};$/d'
    ;;
  */linux-2.6-wireless.patch)
    sedx='
    /^static const u16 rtl8225bcd_rxgain\[/,/^};$/d;
    /^static const u8 rtl8225_agc\[/,/^};$/d;
    /^static const u8 rtl8225_tx_power_cck\[/,/^};$/d;
    /^static const u8 rtl8225_tx_power_cck_ch14\[/,/^};$/d;
    /^static const u16 rtl8225z2_rxgain\[/,/^};$/d;
    /^#define AR5K_RATES_11A /,/^}$/d;
    /^#define AR5K_RATES_11B /,/^}$/d;
    /^#define AR5K_RATES_11G /,/^}$/d;
    /^#define AR5K_RATES_TURBO /,/^}$/d;
    /^#define AR5K_RATES_XR /,/^}$/d;
    /^static const struct ath5k_ini_mode rf5413_ini_mode_end\[/,/^};$/d;
    /^static const struct ath5k_ini ar5212_ini\[/,/^};$/d;
    /^static const struct ath5k_ini_rf rfregs_5111\[/,/^};$/d;
    /^static const struct ath5k_ini_rf rfregs_5112\[/,/^};$/d;
    /^static const struct ath5k_ini_rf rfregs_5112a\[/,/^};$/d;
    /^static const struct ath5k_ini_rf rfregs_5413\[/,/^};$/d;
    /} blinkrates\[\]/,/};$/d;
    '
    ;;
  */linux-2.6-wireless-pending.patch)
    sedx='
    /^#define AR5K_RATES_11A /,/^}$/d;
    /^#define AR5K_RATES_11B /,/^}$/d;
    /^#define AR5K_RATES_11G /,/^}$/d;
    /^#define AR5K_RATES_TURBO /,/^}$/d;
    /^#define AR5K_RATES_XR /,/^}$/d;
    /^static const struct ath5k_ini_mode rf2413_ini_mode_end\[/,/^};$/d;
    '
    ;;
  */linux-2.6-drm-i915-modeset.patch)
    sedx='
    /^static const u32 filter_table\[/,/^};$/d;
    '
    ;;
  esac

  sedx="/^[-]/d; s,^[ +],,; $sedx" 

  case $1 in
  *.bz2) bunzip2 < "$1" | sed "$sedx" ;;
  *.gz) gunzip < "$1" | sed "$sedx" ;;
  *) sed < "$i" "$sedx" ;;
  esac
}
  

n=$#
for i
do
  if xcat "$i" | `dirname $0`/deblob-find-blob |
     grep $verbose_grep .; then
      echo $verbose_msg "$i"
      set fnord "$@" "$i"
      shift
  fi
done
shift $n

exec test $# = 0
